### ISSUE TITLE
osi still uses deprecated glpk apis

### ISSUE THREAD

**Issue by jschueller** [coin-or/Osi#126]
see https://en.wikibooks.org/wiki/GLPK/Using_the_GLPK_callable_library#Deprecated_GLPK_APIs

eg:
```
OsiGlpkSolverInterface.cpp: In member function 'virtual void OsiGlpkSolverInterface::setObjName(std::__cxx11::string)':
OsiGlpkSolverInterface.cpp:3585:3: error: 'lpx_set_obj_name' was not declared in this scope
   lpx_set_obj_name(lp_, const_cast< char * >(name.c_str()));
   ^~~~~~~~~~~~~~~~
OsiGlpkSolverInterface.cpp:3585:3: note: suggested alternative: 'glp_set_obj_name'
   lpx_set_obj_name(lp_, const_cast< char * >(name.c_str()));
```

**Comment by tkralphs** [comment]
Yes, right, which is why our [Glpk wrapper](https://github.com/coin-or-tools/ThirdParty-Glpk) downloads a compatilble version. #121 is a PR to fix this. We'll try to take a look at it, but since that PR is open, I'm going to close this issue.
