### ISSUE TITLE
setInteger: Assertion fails for empty LP

### ISSUE THREAD

**Issue by ClemensBuechner** [coin-or/Osi#129]
I had a use case where I initialized an LP with integer variables and an empty list of constraints. The following assertion failed:
https://github.com/coin-or/Osi/blob/80d92078c88398780c2c748fb982d456c986ed53/src/OsiCpx/OsiCpxSolverInterface.cpp#L1997

My procedure works fine when a trivial constraint like `0 <= infty` considering no variables is in my list of constraints. 
This may be expected behavior, so I don't consider this a bug report.

**Comment by svigerske** [comment]
As far as I see, coltype_ is supposed to be not NULL if there are variables. So maybe somewhere an allocation of that array is missing.
Maybe you can provide some code to reproduce, or hunt down the place where variables are added, but coltype_ remains NULL.

**Comment by ClemensBuechner** [comment]
The following code should reproduce the error:
```
#include <OsiCpxSolverInterface.hpp>

#include <vector>

int main(int argc, const char **argv) {
   OsiCpxSolverInterface *lp_solver = new OsiCpxSolverInterface;
   int num_variables = 1;
   int num_constraints = 0;

   std::vector<double> elements;
   std::vector<int> indices;
   std::vector<int> starts(1, 0);
   std::vector<double> col_lb(num_variables, 0);
   std::vector<double> col_ub(num_variables, 1);
   std::vector<double> objective(num_variables, 1);
   std::vector<double> row_lb(num_constraints, 0);
   std::vector<double> row_ub(num_constraints, 1);

    CoinPackedMatrix matrix(false,
                            num_variables,
                            num_constraints,
                            elements.size(),
                            elements.data(),
                            indices.data(),
                            starts.data(),
                            0);

    lp_solver->loadProblem(matrix,
                           col_lb.data(),
                           col_ub.data(),
                           objective.data(),
                           row_lb.data(),
                           row_ub.data());
    lp_solver->setInteger(0);
    delete lp_solver;
}
```

**Comment by svigerske** [comment]
Thank you, that made it easy to find.
