### ISSUE TITLE
.lp format for clp solver

### ISSUE THREAD

**Issue by yenyi** [coin-or/Osi#130]
Hi,

I'm wondering if the input file can be .lp format?
If yes, then how to use it and put it into the clp solver?
Thank you very much!

**Comment by tkralphs** [comment]
From the command line
```
clp mip-instance.lp
```
should do it. From Osi, use the [readLp](https://github.com/coin-or/Osi/blob/master/src/Osi/OsiSolverInterface.cpp#L1516) method.
