### ISSUE TITLE
Interface for QCQP

### ISSUE THREAD

**Issue by kibaekkim** [coin-or/Osi#133]
I wonder if it makes sense to add Osi functions for QCQP (or QP for now?). For example, https://github.com/coin-or/Smi/blob/master/Smi/src/SmiScnModel.cpp#L589

If it makes sense to add the functions to Osi, I may be able to contribute the implementation.

**Comment by tkralphs** [comment]
There is an [Osi 2](https://github.com/coin-or/Osi2) under development, which is meant to allow interfacing to a much more general class of solvers (general MINLPI believe), but I'm not sure of the current state of things. @mjsaltzman can answer that. In the meantime, you might also look at [OSI CONIC](https://github.com/aykutbulut/OSI-CONIC), which was implemented to support the solution of conic mixed integer problems in [DisCO](https://github.com/coin-or/DisCO). I'm not sure how easy it would be to extend to general QCQP, but I guess conceptually, it might not be too difficult.

**Comment by mjsaltzman** [comment]
This is probably worth doing in the current OSI, and shouldn't be too
hard to port to OSI2 when the time comes.

**Comment by kibaekkim** [comment]
Thank you!
I am closing this, because my question has been answered.
