### ISSUE TITLE
errors threw by OsiGrbSolverInterface GUROBI_CALL

### ISSUE THREAD

**Issue by cheesecakeball** [coin-or/Osi#136]
I am trying to solve a small problem  [farmer.mps.zip](https://github.com/coin-or/Osi/files/4647702/farmer.mps.zip) with a designed error using OsiGrbSolverInterface:

```
#include <iostream>
#include "OsiGrbSolverInterface.hpp"
#include "gurobi_c.h"

int
main(void)
{  
    OsiSolverInterface *si;
    si = new OsiGrbSolverInterface;
    si->readMps("farmer.mps");
    si->setColLower(200, 100000); // this line will create an error, since my instance only have ~20 variables
    si->initialSolve();
    if ( si->isProvenOptimal() ) { 
      std::cout << "Found optimal solution!" << std::endl; 
      std::cout << "Objective value is " << si->getObjValue() << std::endl;

      int n = si->getNumCols();
      const double* solution = si->getColSolution();

      // We can then print the solution or could examine it.
      for( int i = 0; i < n && i < 50; ++i )
         std::cout << si->getColName(i) << " = " << solution[i] << std::endl;
      if( 5 < n )
         std::cout << "..." << std::endl;
   } else {
      std::cout << "Didn't find optimal solution." << std::endl;
      // Could then check other status functions.
   }

   return 0;
}
```

Since `si->setColLower(200, 100000)
` will create an error `Error 10006:Index out of range for attribute 'LB'` from Gurobi function `GRBsetdblattrelement()`, I guess the error message I got `OsiGrbSolverInterface` should also report the error message from the Gurobi call. However, I got the following error from above code:
```
libc++abi.dylib: terminating with uncaught exception of type CoinError
Abort trap: 6
```
It is from line62 of OsiGrbSolverInterface.cpp
`throw CoinError(s, m, "OsiGrbSolverInterface", __FILE__, __LINE__);            \
`
Any idea why this happens? I appreciate your help!

**Comment by svigerske** [comment]
This message should be stored in the CoinError exception that is thrown. You would have to catch it.
```
try
{
  si->setColLower(200, 100000);
}
catch( const CoinError& e )
{ 
  ...
}
```

**Comment by cheesecakeball** [comment]
Thanks for the quick answer! It helps.
