### ISSUE TITLE
configure script doesn't mention flag --with-gurobi-incdir and others in version 0.108.6

### ISSUE THREAD

**Issue by eli-b** [coin-or/Osi#138]
Running `./configure --help` lists an incomplete set of flags. For example, `--with-glpk-incdir` appears in the list but `--with-gurobi-incdir` does not, though both are supported.

In general, I am failing to successfully build Osi with Gurobi support on Linux using coinbrew for the last two days. Had there been a public repository for coinbrew, I would have opened a number of issues for it. For example, running coinbrew in the way the documentation suggests fails during the `coinbrew install ...` stage because the script looks for the main project's version number of each of the dependencies instead of their own version numbers. The way I found around this is to run all three stages in one go: `coinbrew fetch build install ...`.  Running coinbrew with the --with-gurobi-incdir and --with-gurobi-lib flags yields the following error during Osi configuration:
```
checking if user provides library for Gurobi... /home/eli/coin/Osi/Osi/configure: line 11675: cd: yes: No such file or directory
yes
configure: error: Cannot find file gurobi_c.h in /home/eli/coin/build/Osi/0.108.6
```

The pre-built debian packages for Osi don't seem to have Gurobi support.

**Comment by svigerske** [comment]
The configure script in the subdirectory `Osi` should list all (documented) flags.

The public project for coinbrew is https://github.com/coin-or/coinbrew/

It would be good to know what exactly you run to help on this. Osi/configure:11675 in Osi 0.108.6 does have a change-directory (`cd`) command, as far as I see.
https://github.com/coin-or/Osi/blob/releases/0.108.6/Osi/configure#L11662-L11678

**Comment by eli-b** [comment]
Thanks @svigerske, this is the script I'm referring to. Are the Gurobi flags not documented?

I think the `checking if user provides library for Gurobi` part happens around line 23840 of the script.

**Comment by svigerske** [comment]
yes, `Osi/configure --help`:
```
  --with-gurobi-incdir specify the header file directory for library Gurobi
  --with-gurobi-lib specify the flags used to link with the library Gurobi
```
I use
```
--with-gurobi-incdir="/path/to/gurobi/include"
--with-gurobi-lib="-L/path/to/gurobi/libs -lgurobi -lm -lpthread"
```

**Comment by eli-b** [comment]
Those flags don't seem to exist in the latest release 0.108.6. I'll have to build from master.

**Comment by svigerske** [comment]
They exist for Osi 0.108.6.

On master, they are called differently, though.

**Comment by eli-b** [comment]
I can't seem to find mention of gurobi or grb in [https://github.com/coin-or/Osi/blob/releases/0.108.6/configure](https://github.com/coin-or/Osi/blob/releases/0.108.6/configure). I might be missing something.

After running with the flags you provided, should I expect to find OsiGrbSolverInterface.hpp in `dist/include`? I don't seem to get Gurobi-related include files there.

**Comment by svigerske** [comment]
As said before, look at the configure file in the `Osi` subdirectory: https://raw.githubusercontent.com/coin-or/Osi/releases/0.108.6/Osi/configure

If Osi's configure acknowledges the presence of Gurobi, then it should install  OsiGrbSolverInterface.hpp and a libOsiGrb.so library.

**Comment by eli-b** [comment]
Thanks for your time @svigerske. I thought you meant the Osi subdirectory relative to where I'm running coinbrew. It's still a little confusing that the more high-level configure script at the root of the repo mentions some flags like `--with-glpk-incdir` but not others.

For anybody reading this later, I'll mention:
- master is arranged differently. Only a single `configure` script.
- The flags it takes look different

**Comment by tkralphs** [comment]
We are in the midst of a major change in the build infrastructure and the organization of the repos. The current stable version is using the old infrastructure and `master` has been migrated to the new infrastructure. It is admittedly a little confusing right now if you are working with both, but we will document this carefully. 

But let me just add that the easiest thing to do is to use `coinbrew` to get the configure help of the project, then it's uniform no matter what version you are using
```
 coinbrew Osi --configure-help
```

**Comment by eli-b** [comment]
Thanks @tkralphs, that's useful!

I'm very impressed with the dedication of both of you to addressing issues quickly.

I'm still unable to build Osi with Gurobi support, despite being able to link against Gurobi directly in my repo.

With version 0.108.6, I'm getting the following during Osi's configuration after providing `--with-gurobi-incdir="$GUROBI_HOME/include" --with-gurobi-lib="-L$GUROBI_HOME/lib -llibgurobi_c++ -lgurobi"  --with-gurobi`:
```
checking whether symbol GRBloadenv is available with GRB... no
configure: error: Cannot find symbol(s) GRBloadenv with GRB
```

With master and its flags, I'm getting:
```
checking for package Gurobi with function GRBloadenv... no
```

**Comment by svigerske** [comment]
Check the config.log file for why it could not find symbol `GRBloadenv`. Often, this is due to unresolved symbols in third-party libraries, but here it is probably because it cannot find `liblibgurobi_c++.a`.  Since OsiGrb does not use the Gurobi C++ API, you can skip this completely.

There was probably a reason why I mentioned that I also use `-lm -lpthread`.

**Comment by tkralphs** [comment]
`coinbrew` should now print the relevant `config.log` whenever the configuration for a project fails, so just check the last part of the output to see what failed.

**Comment by eli-b** [comment]
Re-running without `-llibgurobi_c++` and with `-lm -lpthread` now. 

Each iteration takes forever because coinbrew warns I should only re-run with a different configuration if I know what I'm doing, and since I clearly don't, I delete all the fetched directories and start from scratch each time.

**Comment by tkralphs** [comment]
It should be OK to just run with `--reconfigure` when the configuration fails and the project has not been built.

**Comment by eli-b** [comment]
Here's the relevant part from `config.log`:
```
configure:11751: checking whether symbol GRBloadenv is available with GRB
configure:11769: gcc -o conftest -O3 -pipe -DNDEBUG -Wimplicit -Wparentheses -Wsequence-point -Wreturn-type -Wcast-qual -Wall -Wno-unknown-pragmas -Wno-long-long   -DOSI_BUILD   conftest.c -L/home/eli/gurobi811/linux64/lib -lgurobi -lm -lpthread  >&5
conftest.c: In function 'main':
conftest.c:38:1: warning: implicit declaration of function 'GRBloadenv' [-Wimplicit-function-declaration]
   38 | GRBloadenv()
      | ^~~~~~~~~~
/usr/bin/ld: cannot find -lgurobi
collect2: error: ld returned 1 exit status
```

I've tried running with and without a `--static` flag and got the same failure.

I re-checked, and `libgurobi.so.8.1.1` is definitely there and sane:
```
> ldd $GUROBI_HOME/lib/libgurobi.so.8.1.1
	linux-vdso.so.1 (0x00007ffc705b1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f41e5151000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f41e512e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f41e5128000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f41e4fd9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f41e4de7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f41e65ea000)
```

**Comment by svigerske** [comment]
But not `libgurobi.so`. Probably there is `libgurobi81.so`, so you want `-lgurobi81`.

Come on. This is the Osi issue tracker.

**Comment by eli-b** [comment]
Sorry, the original issue is definitely resolved.

I'd be happy to move the rest of the comments somewhere more appropriate.

**Comment by tkralphs** [comment]
@eli-b No worries!
