### ISSUE TITLE
Osi with soplex 3.1.1.

### ISSUE THREAD

**Issue by kibaekkim** [coin-or/Osi#2]
I have cloned the master branch. Compiling ``Osi`` with ``soplex 3.1.1.`` resulted in the following error.
```bash
In file included from /homes/kibaekkim/scipoptsuite-5.0.1/soplex/src/spxsolver.h:27:0,
                 from /homes/kibaekkim/scipoptsuite-5.0.1/soplex/src/soplexlegacy.h:25,
                 from /homes/kibaekkim/scipoptsuite-5.0.1/soplex/src/soplex.h:2322,
                 from /homes/kibaekkim/Osi/Osi/src/OsiSpx/OsiSpxSolverInterface.cpp:33:
/homes/kibaekkim/scipoptsuite-5.0.1/soplex/src/spxdefines.h:145:21: error: 'thread_local' does not name a type
 #define THREADLOCAL thread_local
```

I believe that ``Osi`` is incompatible to ``soplex 3.1.1``.

**Comment by tkralphs** [comment]
Generally speaking, I guess the compatible version of SoPlex should be the one mentioned in [ThirdParty/Soplex](https://github.com/coin-or-tools/ThirdParty-SoPlex/blob/master/INSTALL.SoPlex), which seems to be 3.0.0 at the moment. It would be nice to upgrade trunk to compatible with the latest, though. @svigerske @ambros-gleixner

**Comment by svigerske** [comment]
Updating the ThirdParty/SoPlex dependency to use the latest stable (1.6) or release should do it.

**Comment by svigerske** [comment]
However, I'm not sure this will fix the issue from @kibaekkim . What compiler is this? Which version?

**Comment by svigerske** [comment]
Closing as no reply from reporter for a year.

thread_local is C++11, so it requires to have C++11 support enabled in the compiler. For GCC, this has been enabled by default since version 5 (?).
