### ISSUE TITLE
Configuring Osi with Gurobi: implicit declaration vs. pedantic errors

### ISSUE THREAD

**Issue by xammy** [coin-or/Osi#3]
When Osi checks if Gurobi is available, a simple source file that calls an implicitly declared function `GRBloadenv()` to see if that symbol is resolved by linking to libgurobi. Unfortunately, the source file is compiled with `-pedantic-errors`, which makes compilation fail because of the implicit declaration, although Gurobi is there.
A workaround is to comment out the lines in which `-pedantic-errors` is added to the compiler flags in the configure script,

**Comment by svigerske** [comment]
`-pedantic-errors` has been removed (https://github.com/coin-or-tools/BuildTools/commit/21e393d63602c113e2e7ad9cda900cec5b460a8f)
